//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeSplitProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRIP_SPLIT
    {
        public string TRIP_ID { get; set; }
        public string MEMBER_ID { get; set; }
        public string PAYMENT_ID { get; set; }
        public string PAYMENT_DESCRIPTION { get; set; }
        public Nullable<decimal> PAID_COST { get; set; }
    
        public virtual MEMBER MEMBER { get; set; }
    }
}
