//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeSplitProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISIT_LOCATION
    {
        public string TRIP_ID { get; set; }
        public string VISIT_LOC_ID { get; set; }
        public string VISIT_LOC_DESTINATION { get; set; }
        public string VISIT_LOC_DESCRIPTION { get; set; }
        public Nullable<System.DateTime> DATE_BEGIN { get; set; }
        public Nullable<System.DateTime> DATE_FINISH { get; set; }
        public string IMAGE_LINK { get; set; }
    
        public virtual TRIP TRIP { get; set; }
    }
}
