//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeSplitProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WeSplitDBEntities : DbContext
    {
        public WeSplitDBEntities()
            : base("name=WeSplitDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EXPENSE> EXPENSEs { get; set; }
        public virtual DbSet<MEMBER> MEMBERs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TRIP> TRIPs { get; set; }
        public virtual DbSet<TRIP_SPLIT> TRIP_SPLIT { get; set; }
        public virtual DbSet<VISIT_LOCATION> VISIT_LOCATION { get; set; }
    }
}
